version: '3.7'

services:

  rabbitmq:

    restart: always

    build:

      context: .

    container_name: rabbitmq

    image: mateothegreat/docker-alpine-rabbitmq-mqtt:v1

    ports:

      - 5672:5672
      - 15672:15672
      - 61613:61613
